Creating a matrix

In [2]:
import numpy as np
matrix = np.random.uniform(1, 2, size=(20, 5))
print(matrix)

[[1.71088804 1.83247465 1.91408779 1.91603196 1.30794168]
 [1.51911389 1.9810715  1.24850347 1.13953002 1.65965398]
 [1.54426594 1.83379884 1.90661219 1.05898871 1.64428546]
 [1.13291222 1.13684594 1.87236461 1.00148231 1.72692861]
 [1.14330899 1.29517863 1.85762796 1.26077098 1.37489443]
 [1.82397354 1.34854753 1.88526811 1.00559345 1.61151179]
 [1.92506518 1.19625917 1.85415356 1.7631243  1.29336424]
 [1.11171406 1.64526619 1.5781269  1.88191969 1.83460903]
 [1.55196231 1.13357633 1.99405977 1.40028135 1.65407277]
 [1.49444428 1.55732003 1.23772863 1.58171372 1.44610729]
 [1.13788808 1.84646728 1.92931182 1.18500219 1.59798784]
 [1.06635264 1.9726211  1.8919627  1.70128715 1.6766941 ]
 [1.40004566 1.13532385 1.5175228  1.81232176 1.93186416]
 [1.77909306 1.95414253 1.75440068 1.93087588 1.58858227]
 [1.99613736 1.29694052 1.59237837 1.99708169 1.11396382]
 [1.96601677 1.61026146 1.89997507 1.2801851  1.40460624]
 [1.747086   1.22138478 1.1847893  1.31554246 1.63226872]
 [1.35436046 1

Creating a Dataframe 

In [5]:
import pandas as pd
df = pd.DataFrame(matrix, columns=['a', 'b', 'c', 'd', 'e'])
df.head()

a         b         c         d         e
0  1.710888  1.832475  1.914088  1.916032  1.307942
1  1.519114  1.981072  1.248503  1.139530  1.659654
2  1.544266  1.833799  1.906612  1.058989  1.644285
3  1.132912  1.136846  1.872365  1.001482  1.726929
4  1.143309  1.295179  1.857628  1.260771  1.374894

Finding column with max standard deviation

In [10]:
highest_std_col = df.std().idxmax()
print(highest_std_col)

d


Finding row with lowest mean

In [13]:
lowest_mean_row = df.mean(axis=1).idxmin()
print(lowest_mean_row)

19


In [25]:
row = df.iloc[19, :]
print(row)

a    1.984509
b    1.194111
c    1.033226
d    1.239790
e    1.015732
Name: 19, dtype: float64
