The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.  Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [2]:
import numpy as np

# create 1-D array
array1 = np.array([1, 2, 3])

# create 2-D array
array2 = np.array([[1], [2], [3]])

# add arrays of different dimension
sum = array1 + array2

print(sum)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


Numpy automatically expands the size of 1-D array array1 to match with the size of 2-D array array2. 
Then, the element-wise addition is performed between two 2-D arrays.



In [5]:
import numpy as np
a = np.array([10, 2, 3])
b = 2
prod = a * b
print(prod)

[20  4  6]


Here, scalar b get stretched during the arithmetic operation into an array with the same shape as a and then multiplication happened.